name: supa_auth_example
description: "A basic example of SupaAuth."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supaauth:
    path: ../
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  supabase_flutter: ^1.10.25


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true